version: "3"

services:
  blynk-version:
    image: mpherg/blynk-server:latest
    ports:
      - 8080:8080
      - 8441:8441
      - 9443:9443
    volumes:
      - ./data:/data
      - /config
      - ./server.properties:/config/server.properties
    restart: always
    
